### ISSUE TITLE
Installation (macOS 10.14.6): gcc/clang error of igraph on 

### ISSUE THREAD

**Issue by caglorithm** [jajcayn/pygpso#15]
I'm having installation problems of igraph with the following error, linked to [this igraph issue](https://github.com/igraph/python-igraph/issues/208).
```
clang: warning: libstdc++ is deprecated; move to libc++ with a minimum deployment target of OS X 10.9 [-Wdeprecated]
    ld: library not found for -lstdc++
    clang: error: linker command failed with exit code 1 (use -v to see invocation)
    error: command 'gcc' failed with exit status 1
```

Solution:
```
brew install igraph
MACOSX_DEPLOYMENT_TARGET=10.14 pip install python-igraph
```

**Comment by jajcayn** [comment]
thanks for the report!
I'll make `igraph` an optional dependency since only plotting of the optimised ternary tree depends on it and it is rather heavy-weight dependence.

**Comment by jajcayn** [comment]
`igraph` is now optional dependency. cf. #17 and new release (v0.3)
closing this issue
